### ISSUE TITLE
Optional logdet in NetworkGlow 

### ISSUE THREAD

**Issue by flo-he** [slimgroup/InvertibleNetworks.jl#81] opened 2023-04-21 08:40 UTC
Just a small feature request: Giving `NetworkGlow` the option to pass
 ```Julia
NetworkGlow(...; logdet=false)
```
as its building blocks already support this feature.

**Comment by mloubout** [comment] 2023-04-21 11:46
Duplicate of #80 closing, will look into it

**Closed by mloubout** 2023-04-21 11:46 UTC
